#!/bin/bash
sudo apt install -y libncurses-dev python3-dev
cd /var/tmp/ || exit 1
proxychains git clone -b master --depth 1 https://github.com/vim/vim.git || exit 1

cd vim || exit 1
export LDFLAGS="-fno-lto"
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-python3interp=yes \
            --with-python3-config-dir=$(python3-config --configdir) \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 \
            --enable-cscope \
            --prefix=/usr/local
default_vimruntime_dir=$(grep default_vimruntime_dir src/auto/pathdef.c | awk -F'"' '{print $2}')
make VIMRUNTIMEDIR=${default_vimruntime_dir}

sudo make install
sudo ln -sf /usr/local/bin/vim /bin/vi
sudo ln -sf /usr/local/bin/vim /usr/bin/vim
