---
version: "3"

services:
  mynginx:
    image: 10.31.1.205:5000/mynginx:latest
    build:
      context: ./ngx/
      dockerfile: Dockerfile
    container_name: mynginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
       TZ: 'Asia/Shanghai'
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /data/Genie_load/DailyBuild:/www/html/data
      - ./fancyindex:/www/html/data/fancyindex
      - ./.htpasswd:/etc/nginx/.htpasswd
    logging:
       driver: "json-file"
       options:
         max-size: "100m"
    deploy:
       resources:
         limits:
           cpus: '8'
           memory: 8G
         reservations:
           cpus: '2'
           memory: 2G

  mynginx-1081:
    image: 10.31.1.205:5000/mynginx:latest
    container_name: mynginx-1081
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
       TZ: 'Asia/Shanghai'
    ports:
      - "8443:443"
      - "1081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /data:/www/html/data
      - ./fancyindex:/www/html/data/fancyindex
      - ./.htpasswd:/etc/nginx/.htpasswd
    logging:
       driver: "json-file"
       options:
         max-size: "100m"
    deploy:
       resources:
         limits:
           cpus: '8'
           memory: 8G
         reservations:
           cpus: '2'
           memory: 2G
