---
version: "3"

services:
  mynginx:
    image: mynginx:latest
    build:
       context: ./ngx/
       dockerfile: Dockerfile
    container_name: mynginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
       TZ: 'Asia/Shanghai'
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./data:/www/html/data
      - ./.htpasswd:/etc/nginx/.htpasswd
    logging:
       driver: "json-file"
       options:
         max-size: "100m"
    deploy:
       resources:
         limits:
           cpus: '8'
           memory: 8G
         reservations:
           cpus: '2'
           memory: 2G

  mynginx-alpine:
    image: mynginx-alpine:latest
    build:
       context: ./ngx/
       dockerfile: Dockerfile.alpine
    container_name: mynginx-alpine
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
       TZ: 'Asia/Shanghai'
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./data:/www/html/data
      - ./.htpasswd:/etc/nginx/.htpasswd
    logging:
       driver: "json-file"
       options:
         max-size: "100m"
    deploy:
       resources:
         limits:
           cpus: '8'
           memory: 8G
         reservations:
           cpus: '2'
           memory: 2G
