#https://github.com/ajanvier/docker-polr
version: '3.7'

services:
    polr:
        image: ajanvier/polr
        container_name: polr
        restart: always
        ports:
            - "8383:8080"
        env_file:
            - .env
        depends_on:
            - mariadb

    mariadb:
        image: mariadb
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql

