version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: dbpassword
      DB_NAME: wiki
    restart: unless-stopped
    volumes:
      - ./wiki-data:/wiki/data
      - ./.ssh:/home/node/.ssh #主要是ssh config配置和key
    ports:
      - "3000:3000"
