version: '3'
services:
  gitlab:
    image: 'twang2218/gitlab-ce-zh'
    container_name: gitlab
    restart: always
    hostname: '10.12.21.251'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.12.21.251:9001'
        gitlab_rails['gitlab_shell_ssh_port'] = 3022
        unicorn['port'] = 8888
        nginx['listen_port'] = 9001
    ports:
      - '9001:9001'
      - '443:443'
      - '3022:22'
    volumes:
      - /git/gitlab/config:/etc/gitlab
      - /git/gitlab/data:/var/opt/gitlab
      - /git/gitlab/log:/var/log/gitlab
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '12'
          memory: 24G
